{
 "title": "My PC Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "CPU", "query": { "query": "node_cpu_seconds_total" } },
   { "name": "Mode", "query": { "query": "node_cpu_seconds_total" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage - Per CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_cpu_seconds_total{cpu=~\"$CPU\",mode=~\"$Mode\"}[1m])",
     "legendFormat": "CPU {{cpu}} - {{mode}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_interrupts[1m])",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "avg_over_time(vmstat_context_switches[1m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Procs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_running_queue[1m])",
     "legendFormat": "Running Queue"
    },
    {
     "expr": "avg_over_time(vmstat_wait_queue[1m])",
     "legendFormat": "Wait Queue"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_idle_cpu[1m])",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg_over_time(vmstat_sys_cpu[1m])",
     "legendFormat": "System"
    },
    {
     "expr": "avg_over_time(vmstat_usr_cpu[1m])",
     "legendFormat": "User"
    },
    {
     "expr": "avg_over_time(vmstat_waiting_io[1m])",
     "legendFormat": "Waiting IO"
    },
    {
     "expr": "avg_over_time(vmstat_time_stolen_from_vm[1m])",
     "legendFormat": "Time Stolen From VM"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_cached_memory[1m])",
     "legendFormat": "Cached Memory"
    },
    {
     "expr": "avg_over_time(vmstat_virtual_memory[1m])",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "avg_over_time(vmstat_buffer_memory[1m])",
     "legendFormat": "Buffer Memory"
    },
    {
     "expr": "avg_over_time(vmstat_idle_memory[1m])",
     "legendFormat": "Idle  Memory"
    }
   ]
  },
  {
   "title": "Disk Read(s)/Write(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "Disk Reads - {{device}}"
    },
    {
     "expr": "increase(node_disk_written_bytes_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "Disk Writes - {{device}}"
    }
   ]
  },
  {
   "title": "Input/Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_blocks_in[1m])",
     "legendFormat": "Blocks In"
    },
    {
     "expr": "avg_over_time(vmstat_blocks_out[1m])",
     "legendFormat": "Blocks Out"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total[1m])",
     "legendFormat": "Transmit Bytes {{device}}"
    },
    {
     "expr": "increase(node_network_receive_bytes_total[1m])",
     "legendFormat": "Receive Bytes {{device}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(vmstat_swap_in[1m])",
     "legendFormat": "Swpa In"
    },
    {
     "expr": "avg_over_time(vmstat_swap_out[1m])",
     "legendFormat": "Swap Out"
    }
   ]
  }
 ]
}